version: '3.8'

services:
  web:
    build: ./personal_website
    command: gunicorn personal_website.wsgi:application --bind 192.168.1.164:8003
    ports:
      - 8003:8000
#    env_file:
#      - ./.env.prod