version: '3.8'

services:
  web:
    build: ./personal_website
    command: gunicorn personal_website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /home/pi/docker/personal_website_django/personal_website/staticfiles:/usr/src/app/staticfiles/
      - /home/pi/docker/personal_website_django/personal_website/uploads:/usr/src/app/uploads
      - /home/pi/docker/personal_website_django/personal_website/db.sqlite3:/usr/src/app/db.sqlite3
    expose:
      - 8000
    env_file:
      - stack.env  # default name used by portainer for uploaded .env files
  nginx:
    build: ./nginx
    volumes:
      - /home/pi/docker/personal_website_django/personal_website/staticfiles:/usr/src/app/staticfiles/
      - /home/pi/docker/personal_website_django/personal_website/uploads:/usr/src/app/uploads
    ports:
      - 1337:80
    depends_on:
      - web

#volumes:
#  static_volume:
#  media_volume: