version: '3.8'

services:
  web:
    build: ./personal_website
    command: gunicorn personal_website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/home/app/uploads
    expose:
      - 8000
    env_file:
      - stack.env  # default name used by portainer for uploaded .env files
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/home/app/uploads
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: