version: '3.8'

services:
  web:
    build: ./personal_website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./personal_website/:/usr/src/personal_website/
    ports:
      - 8002:8000
    env_file:
      - ./.env.dev