# Generated by Django 4.1.5 on 2023-01-30 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_experience_alter_skill_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='time',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='points',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
