# Generated by Django 4.1.5 on 2023-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_experience_time_experience_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='points',
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.URLField(),
        ),
    ]
