# Generated by Django 4.1.5 on 2023-01-30 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_experience_points_alter_experience_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='exp_type',
            field=models.CharField(choices=[('W', 'Working'), ('E', 'Education')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
