# Generated by Django 4.1.5 on 2023-01-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_experience_points_alter_experience_exp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='points',
        ),
        migrations.AddField(
            model_name='experience',
            name='points',
            field=models.ManyToManyField(to='website.experiencefield'),
        ),
    ]
