# Generated by Django 4.1.5 on 2023-01-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_experiencefield_remove_experience_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='points',
        ),
        migrations.DeleteModel(
            name='ExperienceField',
        ),
        migrations.AddField(
            model_name='experiencepoint',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='website.experience'),
        ),
    ]
