# Generated by Django 4.1.5 on 2023-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_experiencepoint_remove_experience_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='points',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='ExperiencePoint',
        ),
    ]
