# Generated by Django 4.1.5 on 2023-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_experience_points_delete_experiencepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='points',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
