# Generated by Django 4.1.5 on 2023-01-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_experience_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('desc', models.TextField()),
                ('card_pic', models.ImageField(upload_to='')),
                ('pic1', models.ImageField(upload_to='')),
                ('pic2', models.ImageField(upload_to='')),
                ('pic3', models.ImageField(upload_to='')),
            ],
        ),
    ]
