# Generated by Django 4.1.5 on 2023-01-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
