# Generated by Django 4.1.5 on 2023-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ManyToManyField(to='website.category'),
        ),
    ]
