# Generated by Django 4.1.5 on 2023-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('IT', 'IT Skill'), ('L', 'Language Skill')], default='IT', max_length=2),
        ),
    ]
