# Generated by Django 4.1.5 on 2023-02-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_skill_category_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='link',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='place',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='institution',
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('place', models.ManyToManyField(to='website.place')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='institution',
            field=models.ManyToManyField(to='website.institution'),
        ),
    ]
