# Generated by Django 4.1.5 on 2023-02-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_place_remove_experience_link_remove_experience_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='place',
            field=models.ManyToManyField(default='', to='website.place'),
        ),
    ]
