# Generated by Django 4.1.5 on 2023-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_experience_options_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
