# Generated by Django 4.1.5 on 2023-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_testimonial_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
